### ISSUE TITLE
More insults

### ISSUE THREAD

**Issue by tomodachi94** [Tomodachi94/Dash#3]
Hi, community!

We need more insults for `_diss`!

Please no racial slurs or ethnically insensitive insults.

**Comment by xbony2** [comment]
![](https://cdn.discourse.org/turtlerock/uploads/default/original/3X/1/d/1d52ca1497a896ebb05573896ecc0261e1d1be0e.jpg)

**Comment by tomodachi94** [comment]
@xbony2 I don’t think what you tried to do worked...

**Comment by xbony2** [comment]
This is true but I felt it was effective enough of a response to keep up.

**Comment by tomodachi94** [comment]
@xbony2 what *did* you try even?

**Comment by xbony2** [comment]
![](https://cdn.discourse.org/turtlerock/uploads/default/original/3X/1/d/1d52ca1497a896ebb05573896ecc0261e1d1be0e.jpg)

**Comment by tomodachi94** [comment]
@xbony2 if you have any insult ideas please suggest them here or submit a PR.

**Comment by Tomodachi94** [comment]
![Test alt text](https://cdn.discourse.org/turtlerock/uploads/default/original/3X/1/d/1d52ca1497a896ebb05573896ecc0261e1d1be0e.jpg)

**Comment by tomodachi94** [comment]
Enough insults for now. Thank you supporters of Dash!
